import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import uic
from PyQt5.QtGui import QPixmap, QTransform
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel, QFileDialog
from PyQt5.QtGui import QPainter, QColor
from PyQt5.QtWidgets import QTableWidget, QTableWidgetItem

import csv


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(604, 561)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 601, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.Kalendar = QtWidgets.QWidget()
        self.Kalendar.setObjectName("Kalendar")
        self.frame_2 = QtWidgets.QFrame(self.Kalendar)
        self.frame_2.setGeometry(QtCore.QRect(0, 10, 641, 91))
        self.frame_2.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(176, 224, 230);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(30, 30, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.Kalendar)
        self.calendarWidget.setGeometry(QtCore.QRect(30, 130, 341, 311))
        self.calendarWidget.setObjectName("calendarWidget")
        self.tableWidget = QtWidgets.QTableWidget(self.Kalendar)
        self.tableWidget.setGeometry(QtCore.QRect(390, 130, 281, 311))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(23)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tabWidget.addTab(self.Kalendar, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(-10, -20, 601, 521))
        self.frame.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(176, 224, 230);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(140, 70, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lbl_register = QtWidgets.QLabel(self.frame)
        self.lbl_register.setGeometry(QtCore.QRect(40, 20, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_register.setFont(font)
        self.lbl_register.setObjectName("lbl_register")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(140, 240, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ledit_login = QtWidgets.QLineEdit(self.frame)
        self.ledit_login.setGeometry(QtCore.QRect(240, 70, 221, 20))
        self.ledit_login.setObjectName("ledit_login")
        self.ledit_password_2 = QtWidgets.QLineEdit(self.frame)
        self.ledit_password_2.setGeometry(QtCore.QRect(240, 110, 221, 20))
        self.ledit_password_2.setObjectName("ledit_password_2")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(140, 110, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(140, 150, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.ledit_password_3 = QtWidgets.QLineEdit(self.frame)
        self.ledit_password_3.setGeometry(QtCore.QRect(240, 150, 221, 20))
        self.ledit_password_3.setObjectName("ledit_password_3")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(140, 190, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(140, 320, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.ledit_login_2 = QtWidgets.QLineEdit(self.frame)
        self.ledit_login_2.setGeometry(QtCore.QRect(240, 240, 221, 20))
        self.ledit_login_2.setObjectName("ledit_login_2")
        self.btn_register_4 = QtWidgets.QPushButton(self.frame)
        self.btn_register_4.setGeometry(QtCore.QRect(240, 280, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_register_4.setFont(font)
        self.btn_register_4.setObjectName("btn_register_4")
        self.btn_register_5 = QtWidgets.QPushButton(self.frame)
        self.btn_register_5.setGeometry(QtCore.QRect(240, 320, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_register_5.setFont(font)
        self.btn_register_5.setObjectName("btn_register_5")
        self.ledit_password_5 = QtWidgets.QLineEdit(self.frame)
        self.ledit_password_5.setGeometry(QtCore.QRect(240, 190, 221, 20))
        self.ledit_password_5.setObjectName("ledit_password_5")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_2.setGeometry(QtCore.QRect(50, 150, 311, 331))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.frame_5 = QtWidgets.QFrame(self.tab_4)
        self.frame_5.setGeometry(QtCore.QRect(20, 10, 561, 101))
        self.frame_5.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(176, 224, 230);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.lbl_register_3 = QtWidgets.QLabel(self.frame_5)
        self.lbl_register_3.setGeometry(QtCore.QRect(20, 20, 541, 41))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_register_3.setFont(font)
        self.lbl_register_3.setObjectName("lbl_register_3")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 604, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_12.setText(_translate("MainWindow", "Календарь для организации дежурств:"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "10А"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "10Б"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "10В"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "10Г"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "10Д"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "11А"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "11Б"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "11В"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "11Г"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "11Д"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "9A"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "9Б"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "9В"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "9Г"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "9Д"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "8А"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "8Б"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "8В"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "8Д"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "7А"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "7Б"))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "7В"))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "7Г"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Кол-во дежурств"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Неудобные дни"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Kalendar), _translate("MainWindow", "Распределение дежурств"))
        self.label_3.setText(_translate("MainWindow", "Логин:"))
        self.lbl_register.setText(_translate("MainWindow", "Личные данные:"))
        self.label_5.setText(_translate("MainWindow", "Пол:"))
        self.label_7.setText(_translate("MainWindow", "Фамилия:"))
        self.label_8.setText(_translate("MainWindow", "Имя:"))
        self.label_9.setText(_translate("MainWindow", "Отчество:"))
        self.label_4.setText(_translate("MainWindow", "Пароль:"))
        self.btn_register_4.setText(_translate("MainWindow", "Изменить пол"))
        self.btn_register_5.setText(_translate("MainWindow", "Изменить пароль"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Личные данные"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Дата1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Дата2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Дата n"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Класс"))
        self.lbl_register_3.setText(_translate("MainWindow", "Список удтвержденных дежурств:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Список дежурств"))


class WidgetAdmin(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowTitle('DutyManager')

def except_hook(cls, exception, traceback):
    sys.__excepthook__(cls, exception, traceback)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = WidgetAdmin()
    ex.show()
    sys.excepthook = except_hook
    sys.exit(app.exec_())