import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import uic
from PyQt5.QtGui import QPixmap, QTransform
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel, QFileDialog
from PyQt5.QtGui import QPainter, QColor
from PyQt5.QtWidgets import QTableWidget, QTableWidgetItem

import csv


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(578, 577)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 561, 521))
        self.frame.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(176, 224, 230);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(140, 70, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lbl_register = QtWidgets.QLabel(self.frame)
        self.lbl_register.setGeometry(QtCore.QRect(40, 20, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_register.setFont(font)
        self.lbl_register.setObjectName("lbl_register")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(140, 370, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ledit_login = QtWidgets.QLineEdit(self.frame)
        self.ledit_login.setGeometry(QtCore.QRect(130, 90, 221, 20))
        self.ledit_login.setObjectName("ledit_login")
        self.ledit_password = QtWidgets.QLineEdit(self.frame)
        self.ledit_password.setGeometry(QtCore.QRect(130, 140, 221, 20))
        self.ledit_password.setObjectName("ledit_password")
        self.btn_register = QtWidgets.QPushButton(self.frame)
        self.btn_register.setGeometry(QtCore.QRect(170, 470, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_register.setFont(font)
        self.btn_register.setObjectName("btn_register")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(140, 120, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.ledit_password_2 = QtWidgets.QLineEdit(self.frame)
        self.ledit_password_2.setGeometry(QtCore.QRect(130, 190, 221, 20))
        self.ledit_password_2.setObjectName("ledit_password_2")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(140, 170, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(140, 220, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.ledit_password_3 = QtWidgets.QLineEdit(self.frame)
        self.ledit_password_3.setGeometry(QtCore.QRect(130, 240, 221, 20))
        self.ledit_password_3.setObjectName("ledit_password_3")
        self.ledit_password_4 = QtWidgets.QLineEdit(self.frame)
        self.ledit_password_4.setGeometry(QtCore.QRect(130, 290, 221, 20))
        self.ledit_password_4.setObjectName("ledit_password_4")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(140, 270, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(140, 320, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(140, 420, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.ledit_login_2 = QtWidgets.QLineEdit(self.frame)
        self.ledit_login_2.setGeometry(QtCore.QRect(130, 440, 221, 20))
        self.ledit_login_2.setObjectName("ledit_login_2")
        self.btn_register_4 = QtWidgets.QPushButton(self.frame)
        self.btn_register_4.setGeometry(QtCore.QRect(130, 340, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_register_4.setFont(font)
        self.btn_register_4.setObjectName("btn_register_4")
        self.btn_register_5 = QtWidgets.QPushButton(self.frame)
        self.btn_register_5.setGeometry(QtCore.QRect(130, 390, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_register_5.setFont(font)
        self.btn_register_5.setObjectName("btn_register_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 578, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Логин:"))
        self.lbl_register.setText(_translate("MainWindow", "Регистрация:"))
        self.label_5.setText(_translate("MainWindow", "Пол:"))
        self.btn_register.setText(_translate("MainWindow", "Создать аккаунт"))
        self.label_6.setText(_translate("MainWindow", "Код юзера:"))
        self.label_7.setText(_translate("MainWindow", "Фамилия:"))
        self.label_8.setText(_translate("MainWindow", "Имя:"))
        self.label_9.setText(_translate("MainWindow", "Отчество:"))
        self.label_10.setText(_translate("MainWindow", "Класс (при наличии):"))
        self.label_3.setText(_translate("MainWindow", "Пароль:"))
        self.btn_register_4.setText(_translate("MainWindow", "Выбрать"))
        self.btn_register_5.setText(_translate("MainWindow", "Выбрать"))


class Registr(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowTitle('Регистрация')

def except_hook(cls, exception, traceback):
    sys.__excepthook__(cls, exception, traceback)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = Registr()
    ex.show()
    sys.excepthook = except_hook
    sys.exit(app.exec_())
