import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import uic
from PyQt5.QtGui import QPixmap, QTransform
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel, QFileDialog
from PyQt5.QtGui import QPainter, QColor
from PyQt5.QtWidgets import QTableWidget, QTableWidgetItem

import csv


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(702, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 681, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 571, 141))
        self.frame_2.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(176, 224, 230);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(90, 70, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 10, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(100, 140, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_2.setGeometry(QtCore.QRect(360, 250, 311, 281))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(10, 160, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(360, 220, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(10, 240, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(10, 280, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(10, 320, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(120, 250, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 330, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(120, 290, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(-10, -20, 681, 551))
        self.frame.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(176, 224, 230);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(140, 70, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lbl_register = QtWidgets.QLabel(self.frame)
        self.lbl_register.setGeometry(QtCore.QRect(40, 20, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_register.setFont(font)
        self.lbl_register.setObjectName("lbl_register")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(140, 300, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ledit_login = QtWidgets.QLineEdit(self.frame)
        self.ledit_login.setGeometry(QtCore.QRect(240, 70, 221, 20))
        self.ledit_login.setObjectName("ledit_login")
        self.ledit_password_2 = QtWidgets.QLineEdit(self.frame)
        self.ledit_password_2.setGeometry(QtCore.QRect(240, 110, 221, 20))
        self.ledit_password_2.setObjectName("ledit_password_2")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(140, 110, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(140, 150, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.ledit_password_3 = QtWidgets.QLineEdit(self.frame)
        self.ledit_password_3.setGeometry(QtCore.QRect(240, 150, 221, 20))
        self.ledit_password_3.setObjectName("ledit_password_3")
        self.ledit_password_4 = QtWidgets.QLineEdit(self.frame)
        self.ledit_password_4.setGeometry(QtCore.QRect(240, 230, 221, 20))
        self.ledit_password_4.setObjectName("ledit_password_4")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(140, 190, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(140, 230, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(140, 380, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.ledit_login_2 = QtWidgets.QLineEdit(self.frame)
        self.ledit_login_2.setGeometry(QtCore.QRect(240, 300, 221, 20))
        self.ledit_login_2.setObjectName("ledit_login_2")
        self.btn_register_4 = QtWidgets.QPushButton(self.frame)
        self.btn_register_4.setGeometry(QtCore.QRect(240, 340, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_register_4.setFont(font)
        self.btn_register_4.setObjectName("btn_register_4")
        self.btn_register_5 = QtWidgets.QPushButton(self.frame)
        self.btn_register_5.setGeometry(QtCore.QRect(240, 380, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_register_5.setFont(font)
        self.btn_register_5.setObjectName("btn_register_5")
        self.ledit_password_5 = QtWidgets.QLineEdit(self.frame)
        self.ledit_password_5.setGeometry(QtCore.QRect(240, 190, 221, 20))
        self.ledit_password_5.setObjectName("ledit_password_5")
        self.btn_register_6 = QtWidgets.QPushButton(self.frame)
        self.btn_register_6.setGeometry(QtCore.QRect(240, 260, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_register_6.setFont(font)
        self.btn_register_6.setObjectName("btn_register_6")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_4 = QtWidgets.QFrame(self.tab_3)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 671, 521))
        self.frame_4.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(176, 224, 230);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lbl_register_2 = QtWidgets.QLabel(self.frame_4)
        self.lbl_register_2.setGeometry(QtCore.QRect(20, 20, 541, 41))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_register_2.setFont(font)
        self.lbl_register_2.setObjectName("lbl_register_2")
        self.radioButton = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton.setGeometry(QtCore.QRect(70, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_2.setGeometry(QtCore.QRect(70, 140, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_3.setGeometry(QtCore.QRect(70, 180, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_4.setGeometry(QtCore.QRect(70, 260, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_5.setGeometry(QtCore.QRect(70, 300, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_6.setGeometry(QtCore.QRect(70, 220, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setObjectName("radioButton_6")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame_5 = QtWidgets.QFrame(self.tab_4)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 611, 101))
        self.frame_5.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(176, 224, 230);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.lbl_register_3 = QtWidgets.QLabel(self.frame_5)
        self.lbl_register_3.setGeometry(QtCore.QRect(20, 20, 541, 41))
        font = QtGui.QFont()
        font.setFamily("Futura LT")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_register_3.setFont(font)
        self.lbl_register_3.setObjectName("lbl_register_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget.setGeometry(QtCore.QRect(40, 150, 311, 331))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 702, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Дата:"))
        self.label.setText(_translate("MainWindow", "Ближайшее предстоящее дежурство:"))
        self.label_6.setText(_translate("MainWindow", "Дата:"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Фамилия"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Дежурил _ раз"))
        self.label_11.setText(_translate("MainWindow", "Удтвердите трёх учеников на дежурство:"))
        self.label_12.setText(_translate("MainWindow", "Ученики Вашего класса:"))
        self.label_13.setText(_translate("MainWindow", "Ученик 1"))
        self.label_14.setText(_translate("MainWindow", "Ученик 2"))
        self.label_15.setText(_translate("MainWindow", "Ученик 3"))
        self.pushButton.setText(_translate("MainWindow", "Выбрать"))
        self.pushButton_4.setText(_translate("MainWindow", "Выбрать"))
        self.pushButton_5.setText(_translate("MainWindow", "Выбрать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Выбор дежурных"))
        self.label_3.setText(_translate("MainWindow", "Логин:"))
        self.lbl_register.setText(_translate("MainWindow", "Личные данные:"))
        self.label_5.setText(_translate("MainWindow", "Пол:"))
        self.label_7.setText(_translate("MainWindow", "Фамилия:"))
        self.label_8.setText(_translate("MainWindow", "Имя:"))
        self.label_9.setText(_translate("MainWindow", "Отчество:"))
        self.label_10.setText(_translate("MainWindow", "Класс:"))
        self.label_4.setText(_translate("MainWindow", "Пароль:"))
        self.btn_register_4.setText(_translate("MainWindow", "Изменить пол"))
        self.btn_register_5.setText(_translate("MainWindow", "Изменить пароль"))
        self.btn_register_6.setText(_translate("MainWindow", "Изменить класс"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Личные данные"))
        self.lbl_register_2.setText(_translate("MainWindow", "Выберите нежелательные для дежурства дни"))
        self.radioButton.setText(_translate("MainWindow", "Понедельник"))
        self.radioButton_2.setText(_translate("MainWindow", "Вторник"))
        self.radioButton_3.setText(_translate("MainWindow", "Среда"))
        self.radioButton_4.setText(_translate("MainWindow", "Пятница"))
        self.radioButton_5.setText(_translate("MainWindow", "Суббота"))
        self.radioButton_6.setText(_translate("MainWindow", "Четверг"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Нежелательные дни"))
        self.lbl_register_3.setText(_translate("MainWindow", "Список удтвержденных дежурств:"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Дата1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Дата2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Дата n"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Класс"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Список дежурств"))

class WidgetTeacher(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowTitle('DutyManager')

def except_hook(cls, exception, traceback):
    sys.__excepthook__(cls, exception, traceback)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = WidgetTeacher()
    ex.show()
    sys.excepthook = except_hook
    sys.exit(app.exec_())
